package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/aaangelmartin/aka/internal/alias"
	"github.com/aaangelmartin/aka/internal/config"
	"github.com/aaangelmartin/aka/internal/i18n"
	"github.com/aaangelmartin/aka/internal/shellint"
)

func newInstallCmd() *cobra.Command {
	var (
		rcOverride string
	)
	cmd := &cobra.Command{
		Use:   "install [zsh|bash|fish|all]",
		Short: i18n.T("cli.install.short"),
		Long: `Insert a managed block into your shell's rc file that sources the
aliases.<shell> file generated by aka. The block is delimited by markers
(` + shellint.BeginMarker + ` … ` + shellint.EndMarker + `) so it can be updated
or removed cleanly. A timestamped backup is written before any change.

When no argument is given aka installs into the current shell (detected from
$SHELL).`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			target := shellint.DetectShell()
			if len(args) == 1 {
				target = args[0]
			}
			shells := resolveShells(target)
			if len(shells) == 0 {
				return fmt.Errorf("unknown shell %q", target)
			}
			outDir, err := config.OutDir()
			if err != nil {
				return err
			}
			for _, sh := range shells {
				rc := rcOverride
				if rc == "" {
					rc, err = shellint.RCPath(sh)
					if err != nil {
						return err
					}
				}
				action, err := shellint.Install(rc, sh, outDir)
				if err != nil {
					return fmt.Errorf("%s: %w", sh, err)
				}
				fmt.Fprintf(cmd.OutOrStdout(), "%s: %s (%s)\n", sh, action, rc)
			}
			fmt.Fprintln(cmd.OutOrStdout(), i18n.T("msg.install_hint"))
			return nil
		},
	}
	cmd.Flags().StringVar(&rcOverride, "rc", "", "override rc path (only valid with a single shell)")
	return cmd
}

func newUninstallCmd() *cobra.Command {
	var rcOverride string
	cmd := &cobra.Command{
		Use:   "uninstall [zsh|bash|fish|all]",
		Short: i18n.T("cli.uninstall.short"),
		Args:  cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			target := shellint.DetectShell()
			if len(args) == 1 {
				target = args[0]
			}
			shells := resolveShells(target)
			if len(shells) == 0 {
				return fmt.Errorf("unknown shell %q", target)
			}
			for _, sh := range shells {
				rc := rcOverride
				var err error
				if rc == "" {
					rc, err = shellint.RCPath(sh)
					if err != nil {
						return err
					}
				}
				action, err := shellint.Uninstall(rc)
				if err != nil {
					return fmt.Errorf("%s: %w", sh, err)
				}
				fmt.Fprintf(cmd.OutOrStdout(), "%s: %s (%s)\n", sh, action, rc)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&rcOverride, "rc", "", "override rc path")
	return cmd
}

func resolveShells(target string) []string {
	if target == "all" {
		out := make([]string, len(alias.AllShells))
		copy(out, alias.AllShells)
		return out
	}
	if alias.IsValidShell(target) {
		return []string{target}
	}
	return nil
}
