// Package emit generates shell-specific alias files from a slice of Alias.
//
// The source of truth lives in aliases.json (managed by package store); this
// package regenerates a sourceable shell script for each shell (zsh, bash,
// fish) atomically (temp file + rename). aka's rc-file integration adds one
// `source` line pointing at the appropriate file here.
package emit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/aaangelmartin/aka/internal/alias"
)

// Header is the banner written at the top of every generated file.
const Header = `# Generated by aka — do not edit by hand.
# Edit with: aka edit <name>   |   aka   (TUI)
# Source of truth: ~/.local/share/aka/aliases.json
`

// Regenerate writes aliases.zsh, aliases.bash, and aliases.fish under outDir,
// filtering each file to the aliases targeting that shell. outDir is created
// if missing.
func Regenerate(outDir string, aliases []alias.Alias) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	for _, shell := range alias.AllShells {
		path := filepath.Join(outDir, "aliases."+shell)
		if err := writeAtomic(path, Render(shell, aliases)); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

// Render produces the full contents of the alias file for the given shell.
// Aliases not targeting the shell are skipped.
func Render(shell string, aliases []alias.Alias) string {
	var b strings.Builder
	b.WriteString(Header)
	b.WriteString("\n")
	for _, a := range aliases {
		if !a.TargetsShell(shell) {
			continue
		}
		line := renderLine(shell, a)
		if line == "" {
			continue
		}
		if a.Description != "" {
			fmt.Fprintf(&b, "# %s\n", sanitizeComment(a.Description))
		}
		b.WriteString(line)
		b.WriteString("\n")
	}
	return b.String()
}

func renderLine(shell string, a alias.Alias) string {
	switch shell {
	case alias.ShellZsh, alias.ShellBash:
		return fmt.Sprintf("alias %s=%s", a.Name, singleQuote(a.Command))
	case alias.ShellFish:
		return fmt.Sprintf("alias %s %s", a.Name, singleQuote(a.Command))
	default:
		return ""
	}
}

// singleQuote wraps s in single quotes, escaping embedded single quotes with
// the standard POSIX trick (`'\''`). fish accepts the same form.
func singleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// sanitizeComment strips newlines so a multi-line description cannot break out
// of its `# ` comment prefix.
func sanitizeComment(s string) string {
	s = strings.ReplaceAll(s, "\r", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func writeAtomic(path, content string) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".aka-emit-*.tmp")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}
